# Generated by Django 4.2.7 on 2023-11-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shiba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=127)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
