# Generated by Django 4.2.7 on 2023-11-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_main', '0002_shiba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiba',
            name='image_src',
        ),
    ]
